### ISSUE TITLE
Read Sentinel1 GRD file in zip format

### ISSUE THREAD

**Issue by mbenevole** [senbox-org/microwave-toolbox#49]
Sentinel1ProductReaderPlugIn prevents now from reading a Sentinel1 GRD file in zip format. The previous code in s1tbx was :                 if (filename.endsWith(".zip") && filename.startsWith("s1") && !filename.contains("_eta_") &&
                        (ZipUtils.findInZip(path.toFile(), "s1", PRODUCT_HEADER_NAME) ||
                                ZipUtils.findInZip(path.toFile(), "rs2", PRODUCT_HEADER_NAME)) ) {
                    return DecodeQualification.INTENDED;
                }
and is now :                 if (filename.endsWith(".zip") && filename.startsWith("s1") && !filename.contains("_eta_") &&
                        (ZipUtils.findInZip(path.toFile(), "s1", PRODUCT_HEADER_NAME) ||
                                ZipUtils.findInZip(path.toFile(), "rs2", PRODUCT_HEADER_NAME)) &&
                        **!isGRD(path)**) {
                    return DecodeQualification.INTENDED;
Can you explain why ?

**Comment by lveci** [comment]
the GRD reading and in particular the COG GRDs are read using the sar-io-gdal reader

**Comment by mbenevole** [comment]
Ok Luis,

 

Including sar-io-gdal do the job. Thanks.

 

Cordialement 

Michel BÉNET
Tél : +33 (0)9 74 98 15 83


 <http://www.diginove.com/> 

4, rue du Mahatma Gandhi
Espace Beauvalle – Bât. B
13090 Aix-en-Provence
 

 

 

De : Luis Veci ***@***.***> 
Envoyé : mercredi 21 août 2024 22:46
À : senbox-org/microwave-toolbox ***@***.***>
Cc : Michel BENET ***@***.***>; Author ***@***.***>
Objet : Re: [senbox-org/microwave-toolbox] Read Sentinel1 GRD file in zip format (Issue #49)

 

the GRD reading and in particular the COG GRDs are read using the sar-io-gdal reader
