### ISSUE TITLE
"rngfilt" and "azifilt" suffix

### ISSUE THREAD

**Issue by natasnat** [senbox-org/microwave-toolbox#68]
Hi, my workflow doesn't work when I use azimuth and range filters (I want to try hamming weighting, see my graph):

<img width="715" alt="Hamming_Snap2StaMPS_Workflow" src="https://github.com/user-attachments/assets/5ce85aa3-583e-45b8-b3d2-71dc13fd6521">
<img width="401" alt="problem_bennung" src="https://github.com/user-attachments/assets/5a761182-5eab-49de-b641-af005ac8859b">

If I do exactly the same, but without the azimuth and range filters, I have no problems.

I have already tried not to do it as a graph, but step by step, but still the input is not accepted for the interferogram after applying the azimuth and range filters. I think it has something to do with the fact that after applying the filters the bands are renamed as shown in my screenshot with the suffix "_azifilt_rngfilt". My screenshot shows how the bands look before Enhanced-Spectral-Diversity (no problem with interferogram input) and after Enhanced-Spectral-Diversity with Azimuth-Range-Filter (not accepted as interferogram input). 

I have checked the code in github and it is defined: 

    private static final String PRODUCT_NAME = "azimuth_filter";
    private static final String PRODUCT_TAG = "azifilt";
    
    private static final String PRODUCT_NAME = "range_filter";
    private static final String PRODUCT_TAG = "rngfilt";

I think the interferogram input doesn’t know how to process the bands with the suffix “_azifilt_rngfilt”.  

Is this really the problem and how can I fix it? Thanks a lot!

**Comment by dianaharosa** [comment]
@jun--lu

**Comment by natasnat** [comment]
Hey, I already solved it by removing the PRODUCT_TAG and creating the microwave toolbox on my computer with the change, thank you! :)
